export const environment = {
  production: true,
  mocking: false,
  blogConfig: {
    "wpApiKey": "wy1G 60Xi OQ1z 4VA7 o8JN GVLJ",
    "wpUrl": "https://ironplatform.com.uy/wp-json/wp/v2",
    "wpIronStreetCategory": 2,
    "wpIronStreetTag": 3,
    "wpIronStreetWelcomeCategoryId": 85
  },
  osmApiConfig: {
    radioDistanceForInitialData: 25,
    minimunDistanceToBboxContainerDataBorder: 3,
    urlToCustomGeoJsonApi: 'https://overpass-api.de/api/interpreter',
    urlToAllNearDataApi: 'https://api.openstreetmap.org/api/0.6/map?bbox=',
    maxspeedsQuerySelector: '[out:json][timeout:300];nwr["maxspeed"]',
    placesSelector: '[out:json][timeout:6666];nwr',
    outputQueryGeom: 'out geom;',
    osmGeocoderEndpoint: 'https://nominatim.openstreetmap.org/search?q='
  },
  mapboxUserMarkerOptions: {
    positionOptions: {
      enableHighAccuracy: true,
      maximumAge: 0,
      timeout: 6000 /* 6 sec */
    },
    fitBoundsOptions: {
      maxZoom: 15
    },
    trackUserLocation: false,
    showAccuracyCircle: false,
    showUserLocation: true,
    showUserHeading: true
  },
  mapboxMapConfig: {
    accessToken: 'pk.eyJ1IjoibGl0b3hwZXJhbG9jYSIsImEiOiJjbGc3ZW95OGQwNXRtM2V0bHM3ZTcwajVmIn0.rZXdOoZoUFuJ2K4eFyxamg',
    container: 'mapbox',
    style: "mapbox://styles/mapbox/standard",
    //style: "mapbox://styles/litoxperaloca/clun8375j04km01nwcqa93oq7",
    zoom: 0,
    minZoom: 0,
    center: [0, 0],
    pitch: 0,
    bearing: 0,
    hash: false,
    performanceMetricsCollection: false,
    attributionControl: true,
    maxZoom: 20,
    maxPitch: 55,
    projection: 'globe'
  },
  mapboxStylesURLs: {
    '3DMapboxStandard': 'mapbox://styles/mapbox/standard',
    '3DIronStreetDefaultDark': 'mapbox://styles/litoxperaloca/clixdgfzd02ih01p63ec51eu0',
    '3DIronStreetDefaultLight': 'mapbox://styles/litoxperaloca/clixno03g02k901p6agjg4lgd',
    '3DIronStreetCyberPunk': 'mapbox://styles/litoxperaloca/clg6s2tmm00bg01mqol1454ui',
    '3DIronStreetRedRoadsDark': 'mapbox://styles/litoxperaloca/clddmyslc002x01ry4jkrnuvx',
    '3DMapBoxDefaultNavigationDark': 'mapbox://styles/litoxperaloca/clixfsndj02fc01qpgf3x1qwk',
    '2DIronStreetDefaultDark': 'mapbox://styles/litoxperaloca/clixeoyvx02jm01pdcnzl0u8j',
    '2DIronStreetDefaultLight': 'mapbox://styles/litoxperaloca/cliybywv002lj01qpcimhb07l',
    '2DIronStreetCyberPunk': 'mapbox://styles/litoxperaloca/clixfhf2f02it01p6cm5efk6e',
    '2DIronStreetRedRoadsDark': 'mapbox://styles/litoxperaloca/clixfmy1c02go01qpbbdp1lbl',
    '2DMapBoxDefaultStellite': 'mapbox://styles/litoxperaloca/clixnhtko00bx01qqdk95ebfa'
  },
  mapboxControlStyleList: [
    {
      title: '3DMapboxStandard',
      uri: 'mapbox://styles/mapbox/standard',
    }, {
      title: '3DIronStreetDefaultDark',
      uri: 'mapbox://styles/litoxperaloca/clixdgfzd02ih01p63ec51eu0',
    }, {
      title: '3DIronStreetDefaultLight',
      uri: 'mapbox://styles/litoxperaloca/clixno03g02k901p6agjg4lgd',
    }, {
      title: '3DIronStreetCyberPunk',
      uri: 'mapbox://styles/litoxperaloca/clg6s2tmm00bg01mqol1454ui',
    }, {
      title: '3DIronStreetRedRoadsDark',
      uri: 'mapbox://styles/litoxperaloca/clddmyslc002x01ry4jkrnuvx',
    }, {
      title: '3DMapBoxDefaultNavigationDark',
      uri: 'mapbox://styles/litoxperaloca/clixfsndj02fc01qpgf3x1qwk',
    }, {
      title: '2DIronStreetDefaultDark',
      uri: 'mapbox://styles/litoxperaloca/clixeoyvx02jm01pdcnzl0u8j',
    }, {
      title: '2DIronStreetDefaultLight',
      uri: 'mapbox://styles/litoxperaloca/cliybywv002lj01qpcimhb07l',
    }, {
      title: '2DIronStreetCyberPunk',
      uri: 'mapbox://styles/litoxperaloca/clixfhf2f02it01p6cm5efk6e',
    }, {
      title: '2DIronStreetRedRoadsDark',
      uri: 'mapbox://styles/litoxperaloca/clixfmy1c02go01qpbbdp1lbl',
    }, {
      title: '2DMapBoxDefaultStellite',
      uri: 'mapbox://styles/litoxperaloca/clixnhtko00bx01qqdk95ebfa',
    },

  ],
  mapboxControlStylesConf: {
    defaultStyle: "3DMapboxStandard",
    eventListeners: {},
  },
  mapBoxControlGeolocateConfig: {
    positionOptions: {
      enableHighAccuracy: true
    },
    trackUserLocation: true,
    showUserHeading: true,
    showAccuracyCircle: false,
    travelInProgress: false
  },
  mapboxControlDirectionsConfig: {
    accessToken: 'pk.eyJ1IjoibGl0b3hwZXJhbG9jYSIsImEiOiJjbGc3ZW95OGQwNXRtM2V0bHM3ZTcwajVmIn0.rZXdOoZoUFuJ2K4eFyxamg',
    interactive: false,
    profile: "mapbox/driving-traffic",
    unit: "metric",
    language: "es-ES",
    alternatives: true,
    annotations: "maxspeed, distance, duration, congestion, closure",
    banner_instructions: true,
    geometries: "polyline",
    overview: "full",
    steps: true,
    continue_straight: true,
    roundabout_exits: true,
    waypoints_per_route: true,
    coordinates: [-56.147969, -34.88154],
    waypoint_names: "a,b,c",
    voice_instructions: true,
    voice_units: "metric",
    engine: "electric_no_recharge",
    notifications: "all",
    placeholderDestination: "Destino",
    placeholderOrigin: "Origen",
    instructions: {
      showWaypointInstructions: true,
    },
    controls: {
      instructions: true,
      inputs: true,
      profileSwitcher: false
    },
    zoom: 15,
    routePadding: 150,
    congestion: true,
    flyTo: true,
    geocoder: undefined
  },
  mapboxControlNavConfig: {
    visualizePitch: true,
    voiceInstructions: true
  },
  mapboxControlSearchConfig: {
    accessToken: 'pk.eyJ1IjoibGl0b3hwZXJhbG9jYSIsImEiOiJjbGc3ZW95OGQwNXRtM2V0bHM3ZTcwajVmIn0.rZXdOoZoUFuJ2K4eFyxamg',
    mapboxgl: null,
    countries: "uy",
    language: "es",
    placeholder: "Buscar...",
    autocomplete: true
  },
  firebaseConfig: {
    apiKey: "AIzaSyDuG_jOO-S3kO3_h3HKML-6FT5EzJQKH80",
    authDomain: "iron-street.firebaseapp.com",
    databaseURL: "https://iron-street-default-rtdb.firebaseio.com",
    projectId: "iron-street",
    storageBucket: "iron-street.appspot.com",
    messagingSenderId: "648927307257",
    appId: "1:648927307257:web:e21a086fad397f92590928",
    measurementId: "G-DXLP88QG6G"
  },
  recaptcha: {
    key: '6LcUFakmAAAAADV6XQHjGkpkkPj4MsCpm_g3fdVm',
    secret: '6LcUFakmAAAAAB11GNciqZEOTh5zpQkry-m-nt1w',
  },
  openai: {
    key: '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',
    organization: 'IronPlatform',
    organizationId: 'org-IWywnjX9Isu2YYfgRwBooytZ'
  },
  codeToCountryName: {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "DZA": "Algeria",
    "AND": "Andorra",
    "AGO": "Angola",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BRA": "Brazil",
    "BRN": "Brunei",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo (Congo-Brazzaville)",
    "CRI": "Costa Rica",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czechia (Czech Republic)",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "SWZ": "Eswatini (fmr. Swaziland)",
    "ETH": "Ethiopia",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "PRK": "Korea (North)",
    "KOR": "Korea (South)",
    "XKX": "Kosovo",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MHL": "Marshall Islands",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MEX": "Mexico",
    "FSM": "Micronesia",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar (formerly Burma)",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "MKD": "North Macedonia (formerly Macedonia)",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PSE": "Palestine State",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "POL": "Poland",
    "PRT": "Portugal",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "VCT": "Saint Vincent and the Grenadines",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "STP": "Sao Tome and Principe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syria",
    "TWN": "Taiwan",
    "TJK": "Tajikistan",
    "TZA": "Tanzania",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "United States",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VAT": "Vatican City",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe"
  },
  ironUiConfig: {
    categories: [
      // Continuing from other categories already defined...
      {
        name: 'Estaciones de servicio',
        icon: 'water-outline', // Suggest using an appropriate icon
        type: '["amenity"="fuel"]',
        marker: 'ironfuel',
        labelPropertyIndex: 'brand',
        props: {
          "brand": "Marca",
          "brand:wikidata": "Wikidata",
          "name": "Nombre",
          "operator": "Operador",
          "addr:*": "Dirección",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "fuel:diesel": "Diesel",
          "fuel:octane_95": "Nafta 95",
          "fuel:octane_98": "Nafta 98",
          "fuel:lpg": "Gas licuado de petróleo",
          "fuel:cng": "Gas natural comprimido",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "fuel:octane_91": "Nafta 91",
          "fuel:octane_92": "Nafta 92",
          "fuel:octane_93": "Nafta 93",
          "fuel:octane_94": "Nafta 94",
          "fuel:octane_96": "Nafta 96",
          "fuel:octane_97": "Nafta 97",
          "fuel:octane_99": "Nafta 99",
          "fuel:octane_100": "Nafta 100",
          "amenity": "Tipo de estación",
          "compressed_air": "Aire comprimido",
          "ursea:cod_estacion": "Código de estación"
        },

      },
      {
        name: 'Puntos de carga (motores eléctricos)',
        icon: 'battery-charging-outline', // Specific icon for charging stations
        type: '["amenity"="charging_station"]',
        marker: 'ironcharge',
        labelPropertyIndex: 'name',
        props: {
          "amenity": "Tipo de estación",
          "name": "nombre",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "socket:type2": "Tipo de enchufe",
          "socket:output": "Potencia de salida",
          "socket:voltage": "Voltaje",
          "socket:amperage": "Amperaje",
          "socket:mode3": "Modo 3",
          "socket:mode4": "Modo 4",
          "socket:chademo": "CHAdeMO",
          "socket:ccs": "CCS",
          "socket:type1": "Tipo 1",
          "socket:tesla_supercharger": "Supercharger Tesla",
          "socket:tesla_chademo": "CHAdeMO Tesla",
          "socket:tesla_ccs": "CCS Tesla",
          "socket:tesla_type2": "Tipo 2 Tesla",
          "socket:tesla_type1": "Tipo 1 Tesla",
          "socket:tesla_blue": "Tesla Blue",
          "socket:tesla_red": "Tesla Red",
          "socket:tesla_green": "Tesla Green",
          "socket:tesla_gray": "Tesla Gray",
          "socket:tesla_black": "Tesla Black",
          "socket:tesla_white": "Tesla White",
          "socket:tesla_yellow": "Tesla Yellow",
          "socket:tesla_purple": "Tesla Purple",
          "socket:tesla_orange": "Tesla Orange",
          "socket:tesla_pink": "Tesla Pink",
          "socket:tesla_light_blue": "Tesla Light Blue",
          "socket:tesla_light_green": "Tesla Light Green",
          "socket:tesla_light_gray": "Tesla Light Gray",
          "socket:tesla_light_black": "Tesla Light Black",
          "socket:tesla_light_white": "Tesla Light White",
          "socket:tesla_light_yellow": "Tesla Light Yellow",
          "socket:tesla_light_purple": "Tesla Light Purple",
          "socket:tesla_light_orange": "Tesla Light Orange",
          "socket:tesla_light_pink": "Tesla Light Pink",
          "socket:tesla_dark_blue": "Tesla Dark Blue",
          "socket:tesla_dark_green": "Tesla Dark Green",
          "socket:tesla_dark_gray": "Tesla Dark Gray",
          "socket:tesla_dark_black": "Tesla Dark Black",
          "socket:tesla_dark_white": "Tesla Dark White",
          "socket:tesla_dark_yellow": "Tesla Dark Yellow",
          "socket:tesla_dark_purple": "Tesla Dark Purple",
          "socket:tesla_dark_orange": "Tesla Dark Orange",
          "socket:tesla_dark_pink": "Tesla Dark Pink",
          "socket:tesla_medium_blue": "Tesla Medium Blue",
          "socket:tesla_medium_green": "Tesla Medium Green",
          "socket:tesla_medium_gray": "Tesla Medium Gray",
          "socket:tesla_medium_black": "Tesla Medium Black",
          "socket:tesla_medium_white": "Tesla Medium White",
          "socket:tesla_medium_yellow": "Tesla Medium Yellow",
          "socket:tesla_medium_purple": "Tesla Medium Purple",
          "socket:tesla_medium_orange": "Tesla Medium Orange",
          "socket:tesla_medium_pink": "Tesla Medium Pink",
        },
      },
      {
        name: 'Alquiler de automóviles',
        icon: 'car-outline', // Icon that suggests car rental
        type: '["amenity"="car_rental"]',
        marker: 'ironrentcar',
        labelPropertyIndex: 'name',
        props: {
          "amenity": "Tipo de alquiler",
          "name": "nombre",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "rental:bicycle": "Alquiler de bicicletas",
          "rental:car": "Alquiler de autos",
          "rental:truck": "Alquiler de camiones",
          "rental:motorcycle": "Alquiler de motocicletas",
          "rental:boat": "Alquiler de botes",
          "rental:helicopter": "Alquiler de helicópteros",
          "rental:plane": "Alquiler de aviones",
          "rental:equipment": "Alquiler de equipamiento",
          "rental:ski": "Alquiler de esquíes",
          "rental:snowboard": "Alquiler de snowboards",
          "rental:scuba": "Alquiler de equipos de buceo",
          "rental:diving": "Alquiler de equipos de buceo",
          "rental:canoe": "Alquiler de canoas",
          "rental:kayak": "Alquiler de kayaks",
          "rental:surfboard": "Alquiler de tablas de surf",
          "rental:skates": "Alquiler de patines"
        },
      },
      {
        name: 'Estacionamientos',
        icon: 'car-park-outline', // Use an icon that represents parking
        type: '["amenity"="parking"]',
        marker: 'ironparking',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "amenity": "Tipo de estacionamiento",
          "capacity": "Capacidad",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "parking:condition": "Estado del estacionamiento",
          "parking:access": "Acceso",
          "parking:fee": "Tarifa",
          "parking:payment": "Formas de pago",
          "parking:height": "Altura máxima",
          "parking:width": "Ancho máximo",
          "parking:length": "Largo máximo",
          "parking:area": "Área",
          "parking:covered": "Cubierto",
          "parking:surface": "Superficie",
          "parking:level": "Nivel",
          "parking:lane": "Carril",
          "parking:spaces": "Espacios",
          "parking:disabled": "Discapacitados",
          "parking:bicycle": "Estacionamiento de bicicletas",
          "parking:motorcycle": "Estacionamiento de motocicletas",
          "parking:car": "Estacionamiento de autos",
          "parking:truck": "Estacionamiento de camiones",
          "parking:boat": "Estacionamiento de botes"
        },
      },
      {
        name: 'Compras',
        icon: 'cart-outline',
        type: '["shop"~"supermarket|clothes|electronics|furniture|sports|bicycle|books"]',
        marker: 'ironshop',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "shop": "Tipo de tienda",
          "amenity": "Tipo",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:bitcoin": "Pago con Bitcoin",
          "payment:apple_pay": "Pago con Apple Pay",
          "payment:google_pay": "Pago con Google Pay",
          "payment:samsung_pay": "Pago con Samsung Pay",
          "payment:paypal": "Pago con PayPal",
          "payment:alipay": "Pago con Alipay"
        },
      },
      {
        name: 'Salud',
        icon: 'medkit-outline',
        type: '["amenity"~"hospital|clinic|pharmacy|veterinary"]',
        marker: 'ironmed',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "amenity": "Tipo de institución",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "healthcare:speciality": "Especialidad",
          "healthcare:speciality:1": "Especialidad 1",
          "healthcare:speciality:2": "Especialidad 2",
          "healthcare:speciality:3": "Especialidad 3",
          "healthcare:speciality:4": "Especialidad 4",
          "healthcare:speciality:5": "Especialidad 5",
          "healthcare:speciality:6": "Especialidad 6",
          "healthcare:speciality:7": "Especialidad 7",
          "healthcare:speciality:8": "Especialidad 8",
          "healthcare:speciality:9": "Especialidad 9",
          "healthcare:speciality:10": "Especialidad 10",
          "healthcare:speciality:11": "Especialidad 11",
          "healthcare:speciality:12": "Especialidad 12",
          "healthcare:speciality:13": "Especialidad 13",
          "healthcare:speciality:14": "Especialidad 14",
          "healthcare:speciality:15": "Especialidad 15",
        },
      },
      {
        name: 'Educación y Cultura',
        icon: 'school-outline',
        type: '["amenity"~"school|college|university|library|museum|arts_centre|theatre|cinema"]',
        marker: 'ironedu',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "amenity": "Tipo de institución",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "education:level": "Nivel educativo",
          "education:language": "Idioma",
          "education:boarding": "Internado",
        },
      },
      {
        name: 'Servicios Financieros',
        icon: 'cash-outline',
        type: '["amenity"~"bank|atm"]',
        marker: 'ironcash',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "amenity": "Tipo",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:bitcoin": "Pago con Bitcoin"
        },
      },
      {
        name: 'Emergencias, Policía',
        icon: 'alert-circle-outline',
        type: '["amenity"="police"]',
        marker: 'ironpolice',
        labelPropertyIndex: 'name',
        props: {
          "amenity": "Tipo de institución",
          "name": "nombre",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "emergency": "Emergencias",
          "police": "Policía",
          "fire_station": "Estación de bomberos",
          "ambulance_station": "Estación de ambulancias"
        },
      },
      {
        name: 'Deporte y Recreación',
        icon: 'football-outline',
        type: '["sport"~"soccer|basketball|tennis"]',
        marker: 'ironsport',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "sport": "Deporte",
          "surface": "Superficie",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "fee": "Tarifa",
          "lighting": "Iluminación",
          "access": "Acceso",
          "wheelchair": "Accesible para sillas de ruedas",
          "toilets": "Baños",
          "changing_rooms": "Vestuarios",
          "showers": "Duchas",
          "drinking_water": "Agua potable",
          "parking": "Estacionamiento",
          "seats": "Asientos",
          "covered": "Cubierto",
          "amenity": "Tipo de instalación",
          "leisure": "Tipo de recreación",
        },
      },
      {
        name: 'Alojamiento',
        icon: 'bed-outline',
        type: '["tourism"~"hotel|hostel|motel|camp_site|shelter"]',
        marker: 'ironguesthouse',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "tourism": "Tipo de alojamiento",
          "stars": "Estrellas",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "check_in": "Hora de check-in",
          "check_out": "Hora de check-out",
          "fee": "Tarifa",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:bitcoin": "Pago con Bitcoin",
          "amenity": "Tipo de alojamiento",
          "leisure": "Tipo de recreación",
          "shelter": "Refugio",
          "motel": "Motel",
          "hostel": "Hostel",
          "hotel": "Hotel",
          "camp_site": "Camping",
          "guest_house": "Casa de huéspedes",
          "apartment": "Apartamento",
          "chalet": "Cabaña",
          "alpine_hut": "Refugio alpino",
          "wilderness_hut": "Refugio de montaña",
          "caravan_site": "Caravana",
          "cabin": "Cabaña",
          "bungalow": "Bungalow",
          "resort": "Resort",
          "inn": "Posada",
          "bed_and_breakfast": "Bed and Breakfast",
          "camping": "Camping",
        },

      },
      {
        name: 'Alimentación',
        icon: 'restaurant-outline',
        type: '["amenity"~"restaurant|cafe|bar|pub|nightclub|fast_food|food_court"]',
        marker: 'ironfood',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "cuisine": "Tipo de cocina",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "contact:phone": "Teléfono de contacto",
          "opening_hours": "Horario de atención",
          "takeaway": "Takeaway",
          "delivery": "Envío a domicilio",
          "fee": "Tarifa",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:credit_card": "Pago con tarjeta de crédito",
          "payment:credit_cards": "Pago con tarjetas de crédito",
          "payment:debit_cards": "Pago con tarjetas de débito",
          "payment:debit_card": "Pago con tarjeta de débito",
          "source": "Esta información se obtuvo de la siguiente fuente:",
          "smoking": "Permitido fumar",
          "internet_access": "Acceso a internet",
          "drive_through": "Drive-through",
          "outdoor_seating": "Asientos al aire libre",
          "check_date": "Fecha de inspección",
          "check_level": "Nivel de inspección",
          "check_result": "Resultado de inspección",
          "check_up": "Inspección",
          "fee:cash": "Tarifa en efectivo",
          "fee:card": "Tarifa con tarjeta",
          "fee:bitcoin": "Tarifa con Bitcoin",
          "brand": "Marca",
          "brand:wikidata": "Wikidata",
          "brand:wikipedia": "Wikipedia",
          "payment:bitcoin": "Pago con Bitcoin",
          "amenity": "Tipo de establecimiento",
          "restaurant": "Restaurante",
          "cafe": "Cafetería",
          "bar": "Bar",
          "pub": "Pub",
          "nightclub": "Discoteca",
          "fast_food": "Comida rápida",
          "food_court": "Patio de comidas",
          "bakery": "Panadería",
          "butcher": "Carnicería",
          "confectionery": "Confitería",
          "ice_cream": "Heladería",
          "beverages": "Bebidas",
          "food": "Comida",
          "greengrocer": "Verdulería",
          "deli": "Rotisería",
          "supermarket": "Supermarket",
          "kiosk": "Kiosko",
          "marketplace": "Mercado",
          "wine": "Vinos",
          "alcohol": "Alcohol",
          "drinking_water": "Agua potable",
          "water": "Agua",
          "tea": "Té",
          "coffee": "Café",
          "juice": "Jugos",
          "description": "Descripción",
          "diet:vegan": "Vegano",
          "diet:vegetarian": "Vegetariano",
          "diet:gluten_free": "Libre de gluten",
          "diet:organic": "Orgánico",
          "diet:halal": "Halal",
          "diet:kosher": "Kosher",
          "diet:low_fat": "Bajo en grasas",
          "diet:low_salt": "Bajo en sal",
          "diet:low_sugar": "Bajo en azúcar",
          "diet:diabetic": "Diabético",
          "diet:low_carb": "Bajo en carbohidratos",
          "diet:raw": "Crudo",
          "diet:high_fiber": "Alto en fibra",
          "diet:high_protein": "Alto en proteínas",
          "diet:low_calorie": "Bajo en calorías"
        },
      },
      {
        name: 'Teatros',
        icon: 'musical-notes-outline', // Suggests performance arts
        type: '["amenity"="theatre"]',
        marker: 'irontheatre',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "theatre:genre": "Género teatral",
          "theatre:type": "Tipo de teatro",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "fee": "Tarifa",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:bitcoin": "Pago con Bitcoin"
        },
      },
      {
        name: 'Cines',
        icon: 'film-outline', // Directly related to movies
        type: '["amenity"="cinema"]',
        marker: 'ironcine',
        labelPropertyIndex: 'name',
        props: {
          "name": "nombre",
          "cinema:genre": "Género cinematográfico",
          "cinema:type": "Tipo de cine",
          "operator": "Operador",
          "addr:*": "Dirección",
          "addr:city": "Ciudad",
          "addr:country": "País",
          "addr:housenumber": "Número de puerta",
          "addr:state": "Departamento",
          "addr:street": "Calle",
          "website": "Sitio web",
          "phone": "Teléfono",
          "opening_hours": "Horario de atención",
          "fee": "Tarifa",
          "payment:cash": "Pago en efectivo",
          "payment:card": "Pago con tarjeta",
          "payment:bitcoin": "Pago con Bitcoin"
        },
      }
    ]
  }

};
