/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://vqodiicudzaodglg6l22e77glu.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-ixlorll3vncu7h4bepsbh6533y",
  "aws_cognito_identity_pool_id": "us-east-1:08382636-8dfa-443e-888b-e9f83ef74af4",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_RP9JO0604",
  "aws_user_pools_web_client_id": "2skainpdg9bi2hqskpimbsq6fo",
  "oauth": {
    "domain": "6uzfk7tcbwzb-envisbk.auth.us-east-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "https://6uzfk7tcbwzb-envisbk.auth.us-east-1.amazoncognito.com/oauth2/idpresponse,https://ironstreet.com.uy/auth,https://localhost/auth,https://main.dsldx96mlwnk.amplifyapp.com/auth",
    "redirectSignOut": "https://6uzfk7tcbwzb-envisbk.auth.us-east-1.amazoncognito.com/oauth2/idpresponse,https://ironstreet.com.uy/auth,https://localhost/auth,https://main.dsldx96mlwnk.amplifyapp.com/auth",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [
    "FACEBOOK",
    "GOOGLE"
  ],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "geo": {
    "amazon_location_service": {
      "region": "us-east-1",
      "search_indices": {
        "items": [
          "IronStreetPublicSearchLocationIndex-envisbk",
          "IronStreetPublicSearchLocationIndex2-envisbk"
        ],
        "default": "IronStreetPublicSearchLocationIndex-envisbk"
      }
    }
  }
};


export default awsmobile;

