/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "sa-east-1",
  "aws_cognito_identity_pool_id": "sa-east-1:0bd0c5d4-75fb-4060-b668-da65c4497e04",
  "aws_cognito_region": "sa-east-1",
  "aws_user_pools_id": "sa-east-1_PYAIVekJK",
  "aws_user_pools_web_client_id": "47tq6ur0hn4gkobiv03htfjgug",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "geo": {
    "amazon_location_service": {
      "region": "us-east-1",
      "search_indices": {
        "items": [
          "IronStreetPublicSearchLocationIndex-dev",
          "IronStreetPublicSearchLocationIndex2-dev",
          "explore.place.Esri",
          "explore.place.Here"
        ],
        "default": "IronStreetPublicSearchLocationIndex2-dev"
      }
    }
  }
};


export default awsmobile;
